#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@copyright: 2016 Ossi Salmi
@license: MIT <http://www.opensource.org/licenses/mit-license.php>
"""

import os
import sys
import time
import optparse

from collabbackend.clitools import CollabRequest, listAllCollabs
from graphingwiki.editing import get_metas


def main():
    parser = optparse.OptionParser()
    parser.set_usage("%prog [options]")
    parser.add_option("-v", "--verbose",
                      action="store_true", dest="verbose", default=False,
                      help="verbose mode")

    (opts, args) = parser.parse_args()

    for collab in listAllCollabs():
        with CollabRequest(collab) as request:
            metas = get_metas(request.request, "CollabFacts", ["expires"])
        if not metas["expires"]:
            continue

        expires = metas["expires"][0]

        try:
            expires_time = time.mktime(time.strptime(expires, "%Y-%m-%d"))
        except ValueError:
            print >> sys.stderr, \
                "{0}: Invalid expiry date: {1}".format(collab, expires)
            continue

        if expires_time < time.time():
            if opts.verbose:
                print "{0}: Expired on {1}".format(collab, expires)
            else:
                print collab


if __name__ == "__main__":
    if os.getuid() == 0:
        sys.exit("ERROR: {0}: Don't run command as root".format(sys.argv[0]))
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(1)
