#!/bin/sh
# -*- coding: utf-8 -*-

##  @copyright: 2010 by Marko Laakso
##  @license: MIT <http://www.opensource.org/licenses/mit-license.php>

myerr() {
  echo $@ 2>&1
  exit 1
}

if [ `id -u` = 0 ]; then
    myerr "ERROR: $0: Don't run command as root"
fi

CFG=/etc/local/collab/collab.ini

if [ -f ${CFG} ]; then
  . ${CFG} 2> /dev/null
else
  myerr "No ${CFG}"
fi

while getopts "e:y" OPT; do
  case ${OPT} in
    e) ENCRYPT_KEY=${OPTARG} ;;
    y) ASSUME_YES=true ;;
  esac
done

shift $((${OPTIND}-1))

if [ $# -ne 1 ]; then
  myerr "Usage: $0 <collabname>"
fi

umask 007

MYCOLLAB=$1
MYCOLLABWIKIDIR=${wikidir}/${MYCOLLAB}
MYCOLLABHTMLDIR=${htmldir}/${MYCOLLAB}
MYDATE=`date +%F`

mkdir -p ${archivedir}

if [ -d ${MYCOLLABWIKIDIR} ]; then
  cd ${wikidir}
  if [ "x${ENCRYPT_KEY}" != "x" ]; then
    which gpg >/dev/null || exit 1
    gpg --list-public-keys "${ENCRYPT_KEY}" >/dev/null || exit 1
    tar jcvf - ${MYCOLLAB} | gpg -q -e -r "${ENCRYPT_KEY}" \
      -o ${archivedir}/${MYCOLLAB}-${MYDATE}.tar.bz2.gpg
  else
    tar jcvf ${archivedir}/${MYCOLLAB}-${MYDATE}.tar.bz2 ${MYCOLLAB}
  fi
  [ $? -eq 0 ] || exit 1
  if [ "${ASSUME_YES}" = "true" ]; then
    echo "Removing ${MYCOLLABWIKIDIR}"
    sure=y
  else
    echo -n "Remove ${MYCOLLABWIKIDIR}? (y/N) "
    read sure
  fi
  if [ "${sure}blah" = "yblah" ]; then
    rm -rf ${MYCOLLABWIKIDIR}
  fi
else
  echo "ERR: No ${MYCOLLABWIKIDIR}"
fi

if [ -d ${MYCOLLABHTMLDIR} ]; then
  if [ "${ASSUME_YES}" = "true" ]; then
    echo "Removing ${MYCOLLABHTMLDIR}"
    sure=y
  else
    echo -n "Remove ${MYCOLLABHTMLDIR}? (y/N) "
    read sure
  fi
  if [ "${sure}blah" = "yblah" ]; then
    rm -rf ${MYCOLLABHTMLDIR}
  fi
else
  echo "ERR: No ${MYCOLLABHTMLDIR}"
fi

if [ -n "${chatlogdir}" -a -d "${chatlogdir}" ]; then
  CHATLOGDIRS=`cd ${chatlogdir} && ls -d ${MYCOLLAB}@* ${MYCOLLAB}.*@* 2>/dev/null`
  if [ "$?blah" = "0blah" ]; then
    cd "${chatlogdir}"
    tar jcvf ${archivedir}/${MYCOLLAB}-chatlogs-${MYDATE}.tar.bz2 ${CHATLOGDIRS}
    echo "To remove CollabChat logs, run the following commands:"
    for dir in ${CHATLOGDIRS}; do
        echo " rm -rf ${chatlogdir}/${dir}"
    done
  fi
fi
