#!/bin/sh
# -*- coding: utf-8 -*-

##  @copyright: 2010 by Marko Laakso
##  @license: MIT <http://www.opensource.org/licenses/mit-license.php>

myerr() {
  echo $@ 2>&1
  exit 1
}

if [ `id -u` = 0 ]; then
    myerr "ERROR: $0: Don't run command as root"
fi

CFG=/etc/local/collab/collab.ini

if [ -f ${CFG} ]; then
  . ${CFG} 2> /dev/null
else
  myerr "No ${CFG}"
fi

if [ "x$1" = "x-y" ]; then
  ASSUME_YES=true
  shift
fi

if [ $# -ne 1 ]; then
  myerr "Usage: $0 <collabname>"
fi

MYCOLLAB=$1
MYCOLLABWIKIDIR=${wikidir}/${MYCOLLAB}
MYCOLLABHTMLDIR=${htmldir}/${MYCOLLAB}
MYDATE=`date +%F`

mkdir -p ${archivedir}

if [ -d ${MYCOLLABWIKIDIR} ]; then
  cd ${wikidir}
  tar jcvf ${archivedir}/${MYCOLLAB}-${MYDATE}.tar.bz2 ${MYCOLLAB}
  if [ "${ASSUME_YES}" = "true" ]; then
    sure=y
  else
    echo -n "Remove ${MYCOLLABWIKIDIR}? (y/N) "
    read sure
  fi
  if [ "${sure}blah" = "yblah" ]; then
    rm -rf ${MYCOLLABWIKIDIR}
  fi
else
  echo "ERR: No ${MYCOLLABWIKIDIR}"
fi

if [ -d ${MYCOLLABHTMLDIR} ]; then
  if [ "${ASSUME_YES}" = "true" ]; then
    sure=y
  else
    echo -n "Remove ${MYCOLLABHTMLDIR}? (y/N) "
    read sure
  fi
  if [ "${sure}blah" = "yblah" ]; then
    rm -rf ${MYCOLLABHTMLDIR}
  fi
else
  echo "ERR: No ${MYCOLLABHTMLDIR}"
fi

if [ -n "${chatlogdir}" -a -d "${chatlogdir}" ]; then
  CHATLOGDIRS=`cd ${chatlogdir} && ls -d ${MYCOLLAB}@* ${MYCOLLAB}.*@* 2>/dev/null`
  if [ "$?blah" = "0blah" ]; then
    cd "${chatlogdir}"
    tar jcvf ${archivedir}/${MYCOLLAB}-chatlogs-${MYDATE}.tar.bz2 ${CHATLOGDIRS}
    echo "To remove CollabChat logs, run the following commands:"
    for dir in ${CHATLOGDIRS}; do
        echo " rm -rf ${chatlogdir}/${dir}"
    done
  fi
fi
