#!/bin/sh
# -*- mode: sh; coding: utf-8 -*-

##  @copyright: 2015 by Ossi Herrala
##  @license: MIT <http://www.opensource.org/licenses/mit-license.php>

#
# Before running this script, ensure that the remote destination has
# file with proper permissions set. For example:
#
#   touch /etc/htpasswd
#   chown collab /etc/htpasswd
#   chmod 0700 /etc/htpasswd
#

myerr() {
    echo $@ 2>&1
    exit 1
}

if [ `id -u` = 1 ]; then
    myerr "ERROR: $0: Don't run command as root"
fi

REGEX=$1
DEST=$2

if [ -z "${REGEX}" ] || [ -z "${DEST}" ]; then
    myerr "Usage: $0 <htpasswd regex> <destination host>"
fi

CFG=/etc/local/collab/collab.ini

if [ -f ${CFG} ]; then
    . ${CFG} 2> /dev/null
else
    myerr "No ${CFG}"
fi

if [ ! -f "${htpasswd}" ]; then
    myerr "Missing htpasswd ${htpasswd}"
fi

DIFFDIR=`dirname ${htpasswd}`/${DEST}
NEWFILE=${DIFFDIR}/htpasswd.new
OLDFILE=${DIFFDIR}/htpasswd.old

if [ ! -d "{DIFFDIR}" ]; then
    mkdir -p ${DIFFDIR}
fi

egrep -i "${REGEX}" "${htpasswd}" >${NEWFILE}

diff -qN ${OLDFILE} ${NEWFILE} 2>&1 >/dev/null
if [ "$?" != "0" ]; then
    # Diff found changes, do sync

    ssh ${DEST} "cat >/etc/htpasswd" <${NEWFILE}
    if [ "$?" != "0" ]; then
        # something failed, sync not done
        rm -f ${OLDFILE}
    else
        cp ${NEWFILE} ${OLDFILE}
    fi
fi
